/*
  * This file is autogenerated, do NOT edit
  */
  export type FathomRegisteredEventName = 'TX_ERC20_APPROVAL' | 'TX_KPI_TOKEN_CREATION' | 'TX_KPI_TOKEN_REDEMPTION' | 'TX_ORACLE_FINALIZATION' | 'TX_CUSTOM';
  
  export interface FathomSiteEvent {
    id: string;
    object: 'event';
    name: FathomRegisteredEventName;
    currency: string | null
    created_at: string;
  }
  
  export interface FathomSiteInformation {
    siteId: string;
    events: FathomSiteEvent[];
    timestamp: number;
  }
  
  export const siteEvents: FathomSiteInformation = {
  "siteId": "YPUQOWIV",
  "events": [
    {
      "id": "PLDFPLCQ",
      "object": "event",
      "name": "TX_ERC20_APPROVAL",
      "currency": null,
      "created_at": "2023-04-26 15:59:26"
    },
    {
      "id": "5M0DJEML",
      "object": "event",
      "name": "TX_KPI_TOKEN_CREATION",
      "currency": null,
      "created_at": "2023-04-26 15:59:34"
    },
    {
      "id": "I3GDOZLZ",
      "object": "event",
      "name": "TX_KPI_TOKEN_REDEMPTION",
      "currency": null,
      "created_at": "2023-04-26 15:59:43"
    },
    {
      "id": "JFXMREOC",
      "object": "event",
      "name": "TX_ORACLE_FINALIZATION",
      "currency": null,
      "created_at": "2023-04-26 15:59:51"
    },
    {
      "id": "L69JNLCI",
      "object": "event",
      "name": "TX_CUSTOM",
      "currency": null,
      "created_at": "2023-04-27 16:47:13"
    }
  ],
  "timestamp": 1682689137124
};
  
  export function getEventId(event: FathomRegisteredEventName): string | undefined {
    return siteEvents.events.find(siteEvent => siteEvent.name === event)?.id;
  }